### ISSUE TITLE
crossbario/autobahn-js-aarch64:alpine broken

### ISSUE THREAD

**Issue by oberstet** [crossbario/crossbar-docker#37]
```console
time docker build \
	--build-arg AUTOBAHN_JS_VERSION=0.12.0 \
	-t crossbario/autobahn-js-aarch64 \
	-t crossbario/autobahn-js-aarch64:alpine \
	-t crossbario/autobahn-js-aarch64:alpine-0.12.0 \
	-f Dockerfile.alpine .
Sending build context to Docker daemon 3.138 MB
Step 1/16 : FROM aarch64/alpine
 ---> a4c2c01e133b
Step 2/16 : COPY .qemu/qemu-aarch64-static /usr/bin/qemu-aarch64-static
 ---> a22cc0107212
Removing intermediate container fc1769112f10
Step 3/16 : MAINTAINER The Crossbar.io Project <support@crossbario.com>
 ---> Running in 8a3bd29c7d5b
 ---> ac02b9ef9fce
Removing intermediate container 8a3bd29c7d5b
Step 4/16 : ARG AUTOBAHN_JS_VERSION
 ---> Running in 6524d8852e76
 ---> db2c065fbf93
Removing intermediate container 6524d8852e76
Step 5/16 : ENV HOME /app
 ---> Running in 29f6985f01c0
 ---> 61d0489ca0b2
Removing intermediate container 29f6985f01c0
Step 6/16 : ENV DEBIAN_FRONTEND noninteractive
 ---> Running in ac7182b9146d
 ---> dbdb89c472bc
Removing intermediate container ac7182b9146d
Step 7/16 : ENV NODE_PATH /usr/lib/node_modules/
 ---> Running in 43ea1ecc40e3
 ---> 51abd8d36450
Removing intermediate container 43ea1ecc40e3
Step 8/16 : ENV CBURL ws://crossbar:8080/ws
 ---> Running in c3547ee835f6
 ---> 2a25162733b0
Removing intermediate container c3547ee835f6
Step 9/16 : ENV CBREALM realm1
 ---> Running in 15475ebae8c7
 ---> ace48c93b313
Removing intermediate container 15475ebae8c7
Step 10/16 : RUN mkdir /app
 ---> Running in 3662d5fdc243
 ---> d35adbf75165
Removing intermediate container 3662d5fdc243
Step 11/16 : RUN apk add --update nodejs build-base python     && rm -rf /var/cache/apk/*
 ---> Running in 06ea6fd97483
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/aarch64/APKINDEX.tar.gz
(1/34) Installing binutils-libs (2.27-r0)
(2/34) Installing binutils (2.27-r0)
(3/34) Installing gmp (6.1.1-r0)
(4/34) Installing isl (0.17.1-r0)
(5/34) Installing libgomp (6.2.1-r1)
(6/34) Installing libatomic (6.2.1-r1)
(7/34) Installing libgcc (6.2.1-r1)
(8/34) Installing pkgconf (1.0.2-r0)
(9/34) Installing mpfr3 (3.1.5-r0)
(10/34) Installing mpc1 (1.0.3-r0)
(11/34) Installing libstdc++ (6.2.1-r1)
(12/34) Installing gcc (6.2.1-r1)
(13/34) Installing make (4.2.1-r0)
(14/34) Installing musl-dev (1.1.15-r6)
(15/34) Installing libc-dev (0.7-r1)
(16/34) Installing fortify-headers (0.8-r0)
(17/34) Installing g++ (6.2.1-r1)
(18/34) Installing build-base (0.4-r1)
(19/34) Installing ca-certificates (20161130-r1)
(20/34) Installing libcrypto1.0 (1.0.2k-r0)
(21/34) Installing http-parser (2.7.1-r0)
(22/34) Installing libssl1.0 (1.0.2k-r0)
(23/34) Installing libuv (1.9.1-r0)
(24/34) Installing nodejs (6.9.2-r1)
(25/34) Installing libbz2 (1.0.6-r5)
(26/34) Installing expat (2.2.0-r0)
(27/34) Installing libffi (3.2.1-r2)
(28/34) Installing gdbm (1.12-r0)
(29/34) Installing ncurses-terminfo-base (6.0-r7)
(30/34) Installing ncurses-terminfo (6.0-r7)
(31/34) Installing ncurses-libs (6.0-r7)
(32/34) Installing readline (6.3.008-r4)
(33/34) Installing sqlite-libs (3.15.2-r0)
(34/34) Installing python2 (2.7.13-r0)
Executing busybox-1.25.1-r0.trigger
Executing ca-certificates-20161130-r1.trigger
OK: 231 MiB in 45 packages
 ---> 14eb843f2e64
Removing intermediate container 06ea6fd97483
Step 12/16 : RUN npm install -g autobahn@${AUTOBAHN_JS_VERSION}
 ---> Running in cc6018e68f6a
Error: could not get uid/gid
[ 'nobody', 0 ]
qemu: uncaught target signal 11 (Segmentation fault) - core dumped

    at /usr/lib/node_modules/npm/node_modules/uid-number/uid-number.js:37:16
    at ChildProcess.exithandler (child_process.js:213:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

 ---> 1b421278a9e2
Removing intermediate container cc6018e68f6a
Step 13/16 : COPY ./app/* /app/
 ---> c7292a81fdcb
Removing intermediate container b5e21953f0e7
Step 14/16 : VOLUME /app
 ---> Running in b56fd6c920d5
 ---> cc0f2da80b25
Removing intermediate container b56fd6c920d5
Step 15/16 : WORKDIR /app
 ---> 6a01d164135b
Removing intermediate container 4a7ce4e96d6d
Step 16/16 : CMD sh /app/run
 ---> Running in cb68ccd64a9d
 ---> 2274c7bbca0f
Removing intermediate container cb68ccd64a9d
Successfully built 2274c7bbca0f
0.01user 0.00system 1:30.47elapsed 0%CPU (0avgtext+0avgdata 17400maxresident)k
0inputs+0outputs (0major+1512minor)pagefaults 0swaps
(cpy361_1) oberstet@thinkpad-t430s:~/scm/crossbario/crossbar-docker/autobahn-js/aarch64$ 
```

**Comment by oberstet** [comment]
This works now
